# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20160119_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='Test'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Test', max_length=200),
        ),
    ]
