# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20160120_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default='Test'),
        ),
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(default='Test', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(default='Test', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Test', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='website',
            field=models.CharField(default='Test', max_length=200),
        ),
    ]
