# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20160121_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
