# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20160122_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='company_name',
            new_name='platform',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='website',
        ),
    ]
