# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_auto_20160127_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='login',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
