# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_auto_20160128_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='login',
            field=models.CharField(max_length=200),
        ),
    ]
