# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_auto_20160202_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='total',
            field=models.IntegerField(),
        ),
    ]
