# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_auto_20160202_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='login',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], default=None, max_length=1),
        ),
    ]
