# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_auto_20160202_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='loginCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='platformCost',
            field=models.IntegerField(default=0),
        ),
    ]
