# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_auto_20160216_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total',
        ),
        migrations.AlterField(
            model_name='post',
            name='login',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], default=None, max_length=10),
        ),
    ]
