# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_auto_20160216_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='platformCost',
            new_name='androidCost',
        ),
        migrations.AddField(
            model_name='post',
            name='iOSCost',
            field=models.IntegerField(default=0),
        ),
    ]
