# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_auto_20160216_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='login',
            field=models.CharField(choices=[('none', 'none'), ('Yes', 'Yes'), ('No', 'No')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('none', 'none'), ('iOS', 'iOS'), ('Android', 'Android')], default=None, max_length=10),
        ),
    ]
