# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_auto_20160216_0853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
