# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0026_auto_20160217_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='platformCost',
        ),
        migrations.AddField(
            model_name='cost',
            name='AndroidCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cost',
            name='iOSCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='loginCost',
            field=models.IntegerField(default=0),
        ),
    ]
