# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_auto_20160217_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='androidCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Android Cost', editable=False, max_length=20)),
                ('androidCost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='iOSCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='iOS Cost', editable=False, max_length=10)),
                ('iOSCost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='loginCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Login Cost', editable=False, max_length=20)),
                ('loginCost', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
