# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_auto_20160217_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Email Login Cost', editable=False, max_length=20)),
                ('emailCost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='inappCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inapp Cost', editable=False, max_length=20)),
                ('inappCost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='socialLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Social Login Cost', editable=False, max_length=20)),
                ('socialCost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='upfrontCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Upfront Cost', editable=False, max_length=20)),
                ('upfrontCost', models.IntegerField(default=0)),
            ],
        ),
    ]
