# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_emaillogin_inappcost_sociallogin_upfrontcost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emailLogin',
            new_name='emailLoginCost',
        ),
        migrations.RenameModel(
            old_name='socialLogin',
            new_name='socialLoginCost',
        ),
    ]
