# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_auto_20160219_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='beautifulCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costs',
            name='stockCoost',
            field=models.IntegerField(default=0),
        ),
    ]
