# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_auto_20160222_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costs',
            old_name='stockCoost',
            new_name='stockCost',
        ),
    ]
