# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_auto_20160222_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='connectionCost',
            field=models.IntegerField(default=0),
        ),
    ]
