# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0035_auto_20160223_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='QRCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='approvalCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='barcodeCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='cartCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='feedbackCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='galleryCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='managementCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='paymentAdministrationCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='paymentCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='privacyCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='reportingCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='syncCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='taskCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='ticketingCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='userAdminCost',
        ),
        migrations.AddField(
            model_name='costs',
            name='ecommerceCost',
            field=models.IntegerField(default=0, verbose_name='eCommerce Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='androidCost',
            field=models.IntegerField(default=0, verbose_name='Android Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='beautifulCost',
            field=models.IntegerField(default=0, verbose_name='Beautiful Design Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='calendarCost',
            field=models.IntegerField(default=0, verbose_name='Calendar Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='cameraCost',
            field=models.IntegerField(default=0, verbose_name='Camera/Video Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='compassCost',
            field=models.IntegerField(default=0, verbose_name='Compass Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='connectionCost',
            field=models.IntegerField(default=0, verbose_name='Connectivity Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='dashboardCost',
            field=models.IntegerField(default=0, verbose_name='Dashboard Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='emailLoginCost',
            field=models.IntegerField(default=0, verbose_name='Email Login Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='feedCost',
            field=models.IntegerField(default=0, verbose_name='Activity Feed Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='geolocationCost',
            field=models.IntegerField(default=0, verbose_name='GeoLocation Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='iOSCost',
            field=models.IntegerField(default=0, verbose_name='iOS Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='inappCost',
            field=models.IntegerField(default=0, verbose_name='In-app Purchases Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='loginCost',
            field=models.IntegerField(default=0, verbose_name='Login Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='mapsCost',
            field=models.IntegerField(default=0, verbose_name='Maps Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='musicCost',
            field=models.IntegerField(default=0, verbose_name='Audio/Music Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='photosCost',
            field=models.IntegerField(default=0, verbose_name='Camera/Photos Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='ratingCost',
            field=models.IntegerField(default=0, verbose_name='Rating System Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='searchCost',
            field=models.IntegerField(default=0, verbose_name='Search Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='sharingCost',
            field=models.IntegerField(default=0, verbose_name='Social Sharing Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='smsCost',
            field=models.IntegerField(default=0, verbose_name='SMS Integration Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='socialLoginCost',
            field=models.IntegerField(default=0, verbose_name='Social Login Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='stockCost',
            field=models.IntegerField(default=0, verbose_name='Stock Design Cost'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='upfrontCost',
            field=models.IntegerField(default=0, verbose_name='Upfront Cost'),
        ),
    ]
