# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_auto_20160302_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='compassCost',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='photosCost',
        ),
        migrations.AlterField(
            model_name='costs',
            name='ecommerceCost',
            field=models.IntegerField(default=0, verbose_name='Ecommerce Cost'),
        ),
    ]
