# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_auto_20160302_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='webCost',
            field=models.IntegerField(default=0, verbose_name='Web Cost'),
        ),
    ]
