# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_costs_webcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='alotCost',
            field=models.IntegerField(default=0, verbose_name='A lot Cost'),
        ),
        migrations.AddField(
            model_name='costs',
            name='notmuchCost',
            field=models.IntegerField(default=0, verbose_name='Not much Cost'),
        ),
    ]
