# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0039_auto_20160328_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='alotCost',
            field=models.IntegerField(default=0, verbose_name='Great deal of content management'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='androidCost',
            field=models.IntegerField(default=0, verbose_name='Android'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='beautifulCost',
            field=models.IntegerField(default=0, verbose_name='Beautiful design'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='calendarCost',
            field=models.IntegerField(default=0, verbose_name='Calendar'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='cameraCost',
            field=models.IntegerField(default=0, verbose_name='Camera/Video'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='connectionCost',
            field=models.IntegerField(default=0, verbose_name='Connectivity'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='dashboardCost',
            field=models.IntegerField(default=0, verbose_name='Dashboard'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='ecommerceCost',
            field=models.IntegerField(default=0, verbose_name='Ecommerce'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='emailLoginCost',
            field=models.IntegerField(default=0, verbose_name='Email login'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='feedCost',
            field=models.IntegerField(default=0, verbose_name='Activity feed'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='geolocationCost',
            field=models.IntegerField(default=0, verbose_name='Geolocation'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='iOSCost',
            field=models.IntegerField(default=0, verbose_name='iOS'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='inappCost',
            field=models.IntegerField(default=0, verbose_name='In-app purchases'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='loginCost',
            field=models.IntegerField(default=0, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='mapsCost',
            field=models.IntegerField(default=0, verbose_name='Maps'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='musicCost',
            field=models.IntegerField(default=0, verbose_name='Audio/Music'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='notmuchCost',
            field=models.IntegerField(default=0, verbose_name='Not much content management'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='ratingCost',
            field=models.IntegerField(default=0, verbose_name='Rating system'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='searchCost',
            field=models.IntegerField(default=0, verbose_name='Search'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='sharingCost',
            field=models.IntegerField(default=0, verbose_name='Social sharing'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='smsCost',
            field=models.IntegerField(default=0, verbose_name='SMS integration'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='socialLoginCost',
            field=models.IntegerField(default=0, verbose_name='Social login'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='stockCost',
            field=models.IntegerField(default=0, verbose_name='Stock design'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='upfrontCost',
            field=models.IntegerField(default=0, verbose_name='Upfront'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='webCost',
            field=models.IntegerField(default=0, verbose_name='Web'),
        ),
    ]
